version: '3.1'
services: 
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASWORD: root
      MYSQL_TCP_PORT: 3307
      MYSQL_ROOT_PASSWORD: senha123
    ports:
    - "3307:3307"
    volumes:
    - springBoot_data:/var/lib/mysql

volumes:
  springBoot_data: