server:
  error:
    include-stacktrace: ON_PARAM

spring:
  application:
    name: springboot2-essencials
  datasource:
    url: jdbc:mysql://localhost:3307/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: senha123
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app: Spring Boot 2 Essentials By DevDojo
  website: http://devdojo.academy
  github: https://github.com/ronanvcjunior/springboot
